### PR TITLE
build: update maven-download-plugin to 1.4.1

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by gastaldi** [comment]
@ctomc thanks! Can I expect a release soon?

**Comment by ctomc** [comment]
Sure, i will check what other upgrades are available and than do the release

**Comment by gastaldi** [comment]
I'd suggest using https://dependabot.com to automatically receive PRs for library upgrades

**Comment by ctomc** [comment]
dependabot looks interesting, worth looking into it. tnx for tip.
I've released version 28.

**Pull request merged**
