### PR TITLE
[issue#65] bannedRepositories configuration changed based on the plugin documentation

### LINKED ISSUE #65: Enforcer plugin configuration wrongly defines bannedRepository
I experience build failure with error
```quote
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) on project wsat-simple: Unable to parse configuration of mojo org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce for parameter bannedRepositories: Cannot assign configuration entry 'bannedRepositories' with value 'http://*' of type java.lang.String to property of type java.util.List -> [Help 1]
```

The reason seems to be the `bannedRepositories` are configured in wrong way. Based on the documentation at least https://maven.apache.org/enforcer/enforcer-rules/bannedRepositories.html

### PR DESCRIPTION
**Pull request by ochaloup**
fixes #65 

based on https://maven.apache.org/enforcer/enforcer-rules/bannedRepositories.html

### CODE REVIEW

**Comment by darranl** [comment]
Which maven version are you using?

**Comment by ochaloup** [comment]
@darranl correct, I can't reproduce the issue on maven `3.5.2` which I use on my laptop. But our CI fails with older version `3.2.5`. I reproduced the same issue at that maven `3.2.5` on my laptop. The https://github.com/jboss/jboss-parent-pom/issues/65 then fixes this trouble.

```
mvn -version
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /home/jenkins/workspace/btny-pulls-narayana-quickstart/tools/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-693.5.2.el7.x86_64", arch: "amd64", family: "unix"
```

**Comment by darranl** [comment]
That makes more sense, was wondering why we didn't have reports sooner of issues.  

The later maven versions automatically handle it as a single item for the list without error.  I will have a look at merging this for version 36.

**Comment by psakar** [comment]
May be would be better to enforce maven at least 3.3.9
Older version have dependency resolution related issues anyway
According to https://maven.apache.org/docs/history.html version 3.3.9 is already 3 years old
Only reason for 3.2.5 would be java 6 support, but for new versions of projects this is not valid any more, or is it ?

**Comment by ochaloup** [comment]
For our CI I think we have version to support java 6. But I expect I can change the maven version for quickstart compilation.

Anyway, the reported issues is valid, or not? The documentation says there should be used the {{List}}. Or, as the newer versions of maven are capable to work with Strings instead of the List, is it the recommended way how to write a {{pom.xml}} to use directly Strings and not bothering with listing the xml subelements?

**Comment by darranl** [comment]
TBH I think we should go ahead and merge this to bring the configuration in line with the documentation and handle the maven bump as a second step before any tagging if we decide to do that.

**Comment by psakar** [comment]
+1

**Pull request merged**
