### PR TITLE
jboss-parent:40 still manages jdk-misc, but does not define version.jdk-misc anymore

### LINKED ISSUE #236: `jboss-parent:40` still manages `jdk-misc`, but does not define `version.jdk-misc` anymore
It looks like https://github.com/jboss/jboss-parent-pom/commit/13f87e5a3d3f714c2b66221c3b3960b12fb86896#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L185 aimed at removing `jdk-misc` but forgot to remove the managed dependency?

https://github.com/jboss/jboss-parent-pom/blob/d2da46cf8b423e83e24af3eb9960a9b2c8f6e9d2/pom.xml#L777-L786

The current state breaks our BOM flattener in Quarkus CXF and Camel Quarkus, because the `version.jdk-misc` property is not defined anymore.

I assume the proper fix would be to remove the manage dependency too?

### PR DESCRIPTION
**Pull request by ppalaga**
fix #236

### CODE REVIEW

**Review by dmlloyd — APPROVED** [review]
This is mainly a cleanup; having this here doesn't harm anything but it should definitely be removed. LGTM.

**Comment by dmlloyd** [comment]
Actually, not as harmless as I thought!

**Comment by ppalaga** [comment]
Thanks for merging, @dmlloyd! Is there any estimate when we can expect release 41?

**Comment by dmlloyd** [comment]
It's already released, however it will not appear on mirrors until tomorrow. Note that dependabot is already trying to update it on some projects though (with predictable results); tomorrow we can re-run failed jobs on those PRs and hopefully they'll clean up.

**Comment by ppalaga** [comment]
Great to hear that, thanks a lot!

**Pull request merged**
