### PR TITLE
upgraded version.compiler.plugin

### PR DESCRIPTION
**Pull request by mbiarnes**
justification: see https://blog.codefx.org/java/java-11-migration-guide/
JDK11 build friendly

### CODE REVIEW

**Comment by dmlloyd** [comment]
This will now require a 3.8.0-jboss-1 tag for maven-compiler-plugin which has the additionalClassPathItems patch.

**Comment by dmlloyd** [comment]
The 3.8.0-jboss-1 tag is released to our Nexus instance.  Now the PR just has to be updated; I'll go ahead and do that.

**Comment by dmlloyd** [comment]
All set!

**Comment by bartoszmajsak** [comment]
Any chance to contribute it back to the official maven compiler?

**Comment by dmlloyd** [comment]
https://issues.apache.org/jira/browse/MCOMPILER-320

**Comment by ge0ffrey** [comment]
@dmlloyd Thanks for picking this up David!

**Pull request merged**
