### PR TITLE
Forbid JBoss Modules special '_private' packages to be part of generated Javadoc API

### PR DESCRIPTION
**Pull request by ropalka**

### CODE REVIEW

**Comment by ropalka** [comment]
@dmlloyd or @jamezp please review

**Comment by jamezp** [comment]
This would be the first plugin where we explicitly exclude anything by default which concerns me a bit. I do understand the idea, but this moves us slightly in the direction, for javadoc at least, of convention over configuration.

I'm not sure I fully object to it either though.

**Comment by ropalka** [comment]
Neither I am convinced about this @jamezp . I opened this PR to start discussion about it.

**Review by dmlloyd — APPROVED** [review]

**Comment by ropalka** [comment]
It seems both me and David are fine with this JBoss Modules related proposed change @jamezp .

**Comment by jamezp** [comment]
@ropalka I don't have a strong opinion either way. My only point was this is the first time we add non-overridable configuration options to a plugin in the parent.

**Pull request closed without merging**
